name: CI

on:
  push:
    branches: [main1]
  pull_request:
    branches: [main1]
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: use myaction
        uses: wangsongc/myaction@v1.3.11
        with:
          github_token: ${{ secrets.TEST_AUTH_TOKEN }}
          source_repo: 'https://github.com/vuejs/core.git, https://github.com/intlify/vue-i18n-next.git'
          source_branch: 'main, master'
          source_tag: 'v3.2.32, v9.1.8'
          target_repo: 'https://github.com/wangsongc/vue-next.git, https://github.com/wangsongc/vue-i18n-next.git'

      - name: core
        run: |
          cd core
          npm i pnpm -g
          pnpm install
          pnpm test
      - name: vue-i18n-next
        run: |
          cd vue-i18n-next
          yarn
          yarn build
          # 修改核心依赖版本
          sed -i 's|^.*@vue/server-renderer.*$|"@vue/server-renderer": "3.2.31",|' package.json
          sed -i 's|^.*"vue":.*$|"vue": "3.2.31",|' package.json
          yarn
          # yarn test:unit # 有用例因为vue依赖升级导致快照对比失败
          yarn test:e2e
      # - name: router
      #   run: |
      #     cd router
      #     yarn
      #     yarn build
      #     sed -i 's|^.*@vue/compiler-sfc":.*$|"@vue/compiler-sfc": "^3.2.31",|' package.json
      #     sed -i 's|^.*@vue/server-renderer":.*$|"@vue/server-renderer": "^3.2.31",|' package.json
      #     sed -i 's|^.*"vue":.*.,$|"vue": "3.2.31",|' package.json
      #     sed -i 's|^.*"vue":.*."$|"vue": "3.2.31"|' package.json
      #     yarn
      #     yarn test:unit
      #     yarn test:e2e:ci
      # - name: pinia
      #   run: |
      #     cd pinia
      #     yarn
      #     yarn test
