name: update repo

on:
  push:
    branches: [main1]
  pull_request:
    branches: [main1]

jobs:
  core-test:
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.TEST_AUTH_TOKEN }}

    steps:
      - name: test vue
        run: |
          # token/source_url/target_url/project_name/default_branch/tag/
          git clone https://oauth2:${token}@github.com/vuejs/core.git -b main core
          cd core
          git remote set-url origin https://oauth2:${token}@github.com/wangsongc/vue-next.git
          git checkout v3.2.31
          git push origin HEAD:main
          # 执行测试
          npm i pnpm -g
          pnpm install
          pnpm test
          # 同步代码到测试仓
          echo 'done'

      - name: test vue-i18n
        run: |
          git clone https://oauth2:${token}@github.com/intlify/vue-i18n-next.git -b master vue-i18n-next
          cd vue-i18n-next
          git remote set-url origin https://oauth2:${token}@github.com/wangsongc/vue-i18n-next.git
          git checkout v9.1.9
          git push origin HEAD:master
          yarn
          yarn build
          # 修改核心依赖版本
          sed -i 's|^.*@vue/server-renderer.*$|"@vue/server-renderer": "3.2.31",|' package.json
          sed -i 's|^.*"vue":.*$|"vue": "3.2.31",|' package.json
          yarn
          # yarn test:unit # 有用例因为vue依赖升级导致快照对比失败
          yarn test:e2e
          echo 'done'

      - name: test router
        run: |
          git clone https://oauth2:${token}@github.com/vuejs/router.git -b main router
          cd router
          git remote set-url origin https://oauth2:${token}@github.com/wangsongc/router.git
          git checkout v4.0.12
          git push origin HEAD:main
          yarn
          yarn build
          sed -i 's|^.*@vue/compiler-sfc":.*$|"@vue/compiler-sfc": "^3.2.31",|' package.json
          sed -i 's|^.*@vue/server-renderer":.*$|"@vue/server-renderer": "^3.2.31",|' package.json
          sed -i 's|^.*"vue":.*.,$|"vue": "3.2.31",|' package.json
          sed -i 's|^.*"vue":.*."$|"vue": "3.2.31"|' package.json
          yarn
          yarn test:unit
          yarn test:e2e:ci
          echo 'done'

      - name: test pinia
        run: |
          git clone https://oauth2:${token}@github.com/vuejs/pinia.git -b v2 pinia
          cd pinia
          git remote set-url origin https://oauth2:${token}@github.com/wangsongc/pinia.git
          git checkout pinia@2.0.11
          git push origin HEAD:v2
          yarn
          yarn test
          echo 'done'

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
