name: Other project test

on:
  schedule:
    - cron: '00 4 * * 0,1,3,5'
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: 'v1.0.1'

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: update-repo
        uses: wangsongc/batch-update-repo@e0c0881f7b805dad01b798fcc30948eac81525f9
        with:
          github_token: ${{ secrets.TEST_AUTH_TOKEN }}
          source_repo: 'https://github.com/originjs/origin.js.git'
          target_repo: 'https://github.com/wangsongc/origin.js.git'
