name: Other project test

on:
  push:
    paths:
        - '.github/workflows/test.yml'
  schedule:
    - cron: '00 4 * * 0,1,3,5'
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: 'v1.0.1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: origin.js
        uses: wangsongc/batch-update-repo@v1.0.0
        with:
          github_token: ${{ secrets.TEST_AUTH_TOKEN }}
          source_repo: 'https://github.com/originjs/origin.js.git, https://github.com/postcss/postcss.git, https://github.com/FasterXML/stax2-api.git'
          target_repo: 'https://github.com/wangsongc/origin.js.git, https://github.com/wangsongc/postcss.git, https://github.com/wangsongc/stax2-api.git'
